FROM ruby:2.3-alpine

RUN apk add --no-cache \
	git \
	build-base \
	bash

RUN gem install bundler

COPY Gemfile /
RUN bundle install

COPY ./app-tests-example /app-tests
COPY ./docker-entrypoint.sh /docker-entrypoint.sh
COPY ./docker-entrypoint.d/* /docker-entrypoint.d/

WORKDIR /app-tests

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["cucumber"]
